### ISSUE TITLE
CycloneDX 1.4 Schema Support?

### ISSUE THREAD

**Issue by regicsolutions** [TRIMM/plugin-dependencytrack#19]
I know this plug-in is specific to dependency-track but was wondering if it supports the CyloneDX 1.4 schema format? 

https://cyclonedx.org/docs/1.4/json/

**Comment by maaheeb** [comment]
Sorry for my delayed response:
This plugin doesn't have any specific scheme support as the data gets pulled from dependency-track.
Dependency-track supports CycloneDX and i'm pretty sure it does support 1.4. Ingest the BOMs through there and it'll be fine in this plugin.
